blog_mundial/blog_mundial/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('article/', include('article.urls')),
    path('country/', include('country.urls')),
    path('user/', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_mundial/country/urls.py
from django.urls import path
from country import views


app_name = 'country'
urlpatterns = [
    path('country', views.country_list, name='country_list'),
    path('country/add/', views.country_form, name='country-add'),
    path('country/<int:pk>/update', views.update_country, name='country-update'),
    path('country/<int:pk>/delete', views.delete_country, name='country-delete'),
    ]

blog_mundial/home/urls.py
from django.urls import path 
from home import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='main'),
    path('search', views.search, name='search'),
    ]

blog_mundial/country/models.py
from django.db import models

# Create your models here.

class Country(models.Model):
    name = models.CharField(max_length=40)
    country_id = models.IntegerField()
        
    def __str__(self):
        return f'Nombre del país: {self.name}'


blog_mundial/country/forms.py
from unicodedata import name
from django import forms

class CountryForm(forms.Form):
    
    country_name = forms.CharField(label='Pais', max_length=100, min_length=3)
    code = forms.CharField(label='Codigo', max_length=3, min_length=3)    
    

blog_mundial/country/views.py
from django.contrib.auth.decorators import login_required
from django.forms.models import model_to_dict
from django.shortcuts import render


from country.models import Country
from country.forms import CountryForm


# Create your views here.


def country_list(request):
    countries = Country.objects.all()

    context_dict = {
        'countries': countries
    }

    return render(
        request=request,
        context=context_dict,
        template_name="country/country_list.html"
    )

@login_required
def country_form(request):
    if request.method == 'POST':
        country_form = CountryForm(request.POST)
        if country_form.is_valid():
            data = country_form.cleaned_data
            countries.save()

            countries = Country.objects.all()
            context_dict = {
                'countries': countries
            }
            return render(
                request=request,
                context=context_dict,
                template_name="country/country_list.html"
            )

    country_form = CountryForm(request.POST)
    context_dict = {
        'country_form': country_form
    }
    return render(
        request=request,
        context=context_dict,
        template_name='country/country_form.html'
    )


@login_required
def update_country(request, pk: int):
    country = Country.objects.get(pk=pk)

    if request.method == 'POST':
        country_form = CountryForm(request.POST)
        if country_form.is_valid():
            data = country_form.cleaned_data
            country.country_name = data['country_name']
            country.save()

            countries = Country.objects.all()
            context_dict = {
                'countries': countries
            }
            return render(
                request=request,
                context=context_dict,
                template_name="country/country_list.html"
            )

        country_form = CountryForm(model_to_dict(country))
        context_dict = {
            'countries': countries,
            'country_form': country_form,
        }
        return render(
            request=request,
            context=context_dict,
            template_name='country/country_form.html'
        )


@login_required
def delete_country(request, pk: int):
    country = Country.objects.get(pk=pk)
    if request.method == 'POST':
        country.delete()

        country = Country.objects.all()
        context_dict = {
            'countries': countries
        }
        return render(
            request=request,
            context=context_dict,
            template_name="country/country_list.html"
        )

    context_dict = {
        'countries': countries
    }
    return render(
        request=request,
        context=context_dict,
        template_name='country/country_confirm_delete.html',
    )

blog_mundial/country/templates/country/country_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}
{% block blog_mundial_content %}

<h2>Eliminar Pais</h2>
<hr></hr>

<p>Estás seguro de eliminar el pais: {{ country.name }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn2 btn-warning" type="submit" value="Si, eliminar.">
    <a class="btn2 btn-primary" href="{% url 'profesor:country-list' %}" >Cancelar</a>
</form>

{% endblock %}

blog_mundial/country/templates/country/country_edit.html
{% extends "home/index.html" %}

blog_mundial/country/templates/country/country_form.html
{% extends "home/index.html" %}

{% block titulo %} Agregar nuevo país {% endblock %}

{% block blog_mundial_content %} 

<h2>Formulario para agregar nuevo país</h2>

        <hr><hr>   
        <h4 class="card-title">Datos del país</h4>
        <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p }}
            <input type="submit" value="Agregar país"/>
        </form>
    
{% endblock %}

blog_mundial/country/templates/country/country_list.html
{% extends "home/index.html" %}

{% block titulo %} Lista de países {% endblock %}


{% block blog_mundial_content %} 

<h1>Países clasificados</h1>
<p>
 <li>
     {% if countries %}
        {% for country in countries %}
        {{country.name}}
        {% endfor %}
     {% endif %}
 </li>
 <p>
<h2>Añadir país:</h2>
<div>
    <a name="" id="" class="btn btn-succees" href="{% url 'country:country-add' %}" role="button">Añadir nuevo país</a>
</div>


{% endblock %}