blog_mundial/article/urls.py
from django.urls import path
from article import views
from django.conf.urls import include

app_name = 'article'
urlpatterns = [
    path('article', views.article_list, name='article_list'),
    path('article/add/', views.article_form, name='article_form'),
    path('article/<int:pk>/detail', views.article_detail, name='article-detail'),
    # path('article/<int:pk>/update', views.ArticleUpdateView.as_view(), name='article-update'),
    # path('article/<int:pk>/delete', views.ArticleDeleteView.as_view(), name='article-delete'),
    path(r'ckeditor/', include('ckeditor_uploader.urls')),
    ]
    

blog_mundial/blog_mundial/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('article/', include('article.urls')),
    path('country/', include('country.urls')),
    path('user/', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_mundial/country/urls.py
from django.urls import path
from country import views


app_name = 'country'
urlpatterns = [
    path('country', views.country_list, name='country_list'),
    path('country/add/', views.country_form, name='country-add'),
    path('country/<int:pk>/update', views.update_country, name='country-update'),
    path('country/<int:pk>/delete', views.delete_country, name='country-delete'),
    ]

blog_mundial/home/urls.py
from django.urls import path 
from home import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='main'),
    path('search', views.search, name='search'),
    ]

blog_mundial/user/urls.py
from django.urls import path

from user import views


app_name='user'
urlpatterns = [
    path('login', views.login_request, name='user-login'),
    path('logout', views.logout_request, name='user-logout'),
    path('register', views.register, name='user-register'),
    path('register/update', views.user_update, name='user-update'),
    path('avatar/load', views.avatar_load, name='avatar-load'),
]

blog_mundial/home/models.py
from django.db import models

# Create your models here.

blog_mundial/home/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.db.models import Q

from article.models import Article
from user.models import Avatar


def home(request):
    avatar_ctx = get_avatar_url_ctx(request)
    context_dict = {**avatar_ctx}
    articles = Article.objects.all()
    context_dict.update({
        'articles': articles,
                        })
    print('context_dict: ', context_dict)
    return render(
        request=request,
        context=context_dict,
        template_name="home/main.html"
    )
    


def get_avatar_url_ctx(request):
    avatars = Avatar.objects.filter(user=request.user.id)
    if avatars.exists():
        return {"url": avatars[0].image.url}
    return {}


def search(request):
    avatar_ctx = get_avatar_url_ctx(request)
    context_dict = {**avatar_ctx}
    if request.GET['search_param']:
        search_param = request.GET['search_param']
        query = Q(name__contains=search_param)
        query.add(Q(code__contains=search_param), Q.OR)
        articles = Article.objects.filter(query)
        context_dict.update({
        'articles': articles,
        'search_param': search_param,
        })
    return render(
        request=request,
        context=context_dict,
        template_name="article_list.html",
    )


blog_mundial/home/templates/home/index.html
<!Doctype html> 

<html lang="en">
  {% load static %}

  <head>
        
    <title>{% block titulo %} {{ settings.APP_NAME }} {% endblock %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS v5.2.0-beta1 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"  integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

  </head>
  <body style="background-color: blue;">

            
    <nav class="navbar navbar-expand navbar-light bg-light">
        <div class="container-fluid d-flex">
            <a class="nav-item nav-link active" href="{% url 'home:main' %}">Home </a>
            <a class="nav-item nav-link" href="{% url 'article:article_list' %}">Articulos</a>
            <a class="nav-item nav-link" href="{% url 'country:country_list' %}">Paises</a>
            {% if user.is_authenticated %}
                <a class="btn btn-secondary" href="{% url 'user:user-update' %}">Editar usuario</a>
                <a class="btn btn-primary" href="{% url 'user:user-logout' %}">Cerrar Sesión</a>
                {% else %}
                <a class="btn btn-primary" href="{% url 'user:user-login' %}">Iniciar Sesión</a>
            {% endif %}
            
        </div>
    </nav>

    <!-- Masthead-->
    <header class="masthead">
      <div class="container position-relative">
          <div class="row justify-content-center">
              <div class="col-xl-6">
                  <div class="text-center text-white">
                      <!-- Page heading-->
                      <h1 class="mb-5"> Bienvenido al blog mundial <br> Proyecto Vega-Liberal</h1>
                      {% if messages %}
                          {% for message in messages %}
                          <h4><p style="color: rgb(111, 131, 0)" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p></h4>
                          {% endfor %}
                      {% endif %}
                      <div class="text-lg-start text-white">

    
    <div class="container">
        <div class="row">
            <div class="col-12">
                {% block blog_mundial_content %} 
                
                {% endblock %}
            </div>
        </div>
    </div>
    <footer class="footer dark-light">
        <div class="container">
            {% if user.is_superuser %}
                <h5><p style="color: red">SuperUser</p><h5>
            {% else %}
                <h5><p style="color: red">Not SuperUser</p><h5>
            {% endif %}
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                    <ul class="list-inline mb-2">
                        <li class="list-inline-item"><a href="#!">About</a></li>
                        <li class="list-inline-item">⋅</li>
                        <li class="list-inline-item"><a href="#!">Contact</a></li>
                        <li class="list-inline-item">⋅</li>
                        <li class="list-inline-item"><a href="#!">Terms of Use</a></li>
                        <li class="list-inline-item">⋅</li>
                        <li class="list-inline-item"><a href="#!">Privacy Policy</a></li>
                    </ul>
                    <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2022. All Rights Reserved.</p>
                </div>
                <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item me-4">
                            <a href="#!"><i class="bi-facebook fs-3"></i></a>
                        </li>
                        <li class="list-inline-item me-4">
                            <a href="#!"><i class="bi-twitter fs-3"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!"><i class="bi-instagram fs-3"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'home/js/scripts.js' %}"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>

</html>

blog_mundial/home/templates/home/main.html
{% extends "home/index.html" %}
{% load static %}

{% block blog_mundial_content %}



{% if user.is_authenticated %}
<div class="text-center">
    <h2>Bienvenido {{ user.username }}</h2>
    <h3><a style="color: rgb(3, 36, 184)" href="{% url 'user:avatar-load' %}">Cambiar Avatar</a></h3>
    <img height="160px" src="{{url}}" alt="">
</div>
{% endif %}

<h2>Buscador de Artículos</h2>
<hr>
</hr>

<form action="/search" method="GET">
    <div>
        <input type="text" name="search_param" id="article_code_or_name" placeholder="Buscar.."
        {% if search_param %} value="{{ search_param }}" {% endif %} />   
        
        <input type="submit" value="Buscar">
        <a style="color: blue" href="{% url 'home:main' %}"><i class="fa fa-undo"></i></a>
    </div>

</form>
<hr>
</hr>


{% endblock %}