blog_mundial/article/urls.py
from django.urls import path
from article import views
from django.conf.urls import include

app_name = 'article'
urlpatterns = [
    path('article', views.article_list, name='article_list'),
    path('article/add/', views.article_form, name='article_form'),
    path('article/<int:pk>/detail', views.article_detail, name='article-detail'),
    # path('article/<int:pk>/update', views.ArticleUpdateView.as_view(), name='article-update'),
    # path('article/<int:pk>/delete', views.ArticleDeleteView.as_view(), name='article-delete'),
    path(r'ckeditor/', include('ckeditor_uploader.urls')),
    ]
    

blog_mundial/blog_mundial/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('article/', include('article.urls')),
    path('country/', include('country.urls')),
    path('user/', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_mundial/home/urls.py
from django.urls import path 
from home import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='main'),
    path('search', views.search, name='search'),
    ]

blog_mundial/article/models.py
from django.db import models

from ckeditor.fields import RichTextField

# Create your models here.
class Article(models.Model):
    name = models.CharField(max_length=40)
    description = models.CharField(max_length=200, blank=True)
    country = models.CharField(max_length=20)
    article_id = models.IntegerField()
    #article_content = models.TextField(max_length=1200)
    article_content = RichTextField('Escriba aqui su articulo')


    def __str__(self):
        return f'Nombre del Artículo: {self.name} País sobre el artículo: {self.country} '

blog_mundial/article/forms.py
from django import forms

from ckeditor.fields import RichTextField


class ArticleForm(forms.Form):
    name = forms.CharField(max_length=40, label='Titulo')
    country = forms.CharField(max_length=20, label='País')
    article_id = forms.IntegerField(label='ID')
    article_content = forms.CharField(widget=forms.Textarea, label='Contenido')
    

blog_mundial/article/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required
from django.forms.models import model_to_dict

from article.forms import ArticleForm

from article.models import Article


# Create your views here.

def article_list(request):
    articles = Article.objects.all()

    context_dict = {
        'articles': articles
    }

    return render(
        request=request,
        context=context_dict,
        template_name="article/article_list.html"
    )

@login_required
def article_form(request):
    if request.method == 'POST':
        articles = Article(request.POST)
        if articles.is_valid():
            data = articles.cleaned_data()
            
            articles = Article(
                name=data['name'],
                description=data['description'],
                country=data['country'],
                article_id=data['article_id'],
                article_content=data['article_content']
                )
            context_dict = {
                'articles': articles              
                }
            
            articles.save()
            return render (request, 'article/article_list.html', context_dict )

        article_form = ArticleForm(request.POST)
        context_dict = {
        'article_form': article_form
            }
        article_form.save()
        return render(
                request=request,
                context=context_dict,
                template_name="article/article_form.html"
            )


def article_detail(request, article_id):
    articles = Article.objects.get(pk=article_id)
    context_dict = {
        'articles': articles
    }
    return render(
        request=request,
        context=context_dict,
        template_name='article/article_detail.html'
    )




blog_mundial/article/templates/article/article_edit.html
{% extends "home/index.html" %}

{% block titulo %} Editar artículo {% endblock %}

{% block contenido %} 

<h2>Formulario para editar artículo</h2>

<div class="card">
    <div class="card-header">
        Editar un artículo
    </div>
    <div class="card-body">
        <h4 class="card-title">Datos del artículo</h4>
        <form enctype="multipart/form-data" method="post">
    
            <div class="mb-3">
              <label for="" class="form-label">Nombre:</label>
              
              <input type="text"
                class="form-control" name="" id="" aria-describedby="helpId" placeholder="Nombre">
            
            </div>
        </form>
    </div>
    <div class="card-footer text-muted">
    </div>
</div>

{% endblock %}

blog_mundial/article/templates/article/article_form.html
{% extends "home/index.html" %}
{% load static %}
{% block blog_mundial_content %}

<h2>Formulario para crear/editar articulo</h2>
<hr></hr>
{% if article_form.errors %}

<p style=color:red;>Revisar los datos ingresados</p>

{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    {{ article_form.media }}
    {{ article_form.as_p }}
    <input type="submit" class="btn btn-primary" value="Guardar articulo" />
</form>

{% endblock %}

blog_mundial/article/templates/article/article_list.html
{% extends "home/index.html" %}

{% block titulo %} Lista de artículos {% endblock %}
    

{% block blog_mundial_content %} 

<h1>Sección de artículos.</h1>
<p>
    Aquí podrá encontrar los artículos que ha escrito el autor.
    {% if articles %}
        <li>{{article.title}}</li>
    {% else %}
        <p>No hay artículos para mostrar.</p>
    {% endif %}
    
<h2>Lista de artículos:</h2>
{% if user.is_authenticated %} 
<a class="card_custom" href="{% url 'article:article_form' %}">Crear nuevo Articulo</a>
{% endif %}
<hr></hr>
<ul>
    {% for article in article_list %}
    <li>
        {{articles}}
        (
            <a href="{% url 'article:article-detail' article.id %}">
                <i class="fa fa-eye" style="color: rgb(0, 0, 255);"> </i>
            </a>
        {% if user.is_authenticated %} 
        |
        <a href="{% url 'article:article-update' article.id %}">
            <i class="fa fa-pencil" style="color: rgb(0, 0, 190);"> </i>
        </a>
        |
        <a href="{% url 'article:article-delete' article.id %}">
            <i class="fa fa-trash" style="color: rgb(0, 0, 100);"> </i>
        </a>
        {% endif %}
        )
    </li>
    {% endfor %}
</ul>

{% endblock %}