blog_mundial/blog_mundial/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('article/', include('article.urls')),
    path('country/', include('country.urls')),
    path('user/', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_mundial/home/urls.py
from django.urls import path 
from home import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='main'),
    path('search', views.search, name='search'),
    ]

blog_mundial/user/urls.py
from django.urls import path

from user import views


app_name='user'
urlpatterns = [
    path('login', views.login_request, name='user-login'),
    path('logout', views.logout_request, name='user-logout'),
    path('register', views.register, name='user-register'),
    path('register/update', views.user_update, name='user-update'),
    path('avatar/load', views.avatar_load, name='avatar-load'),
]

blog_mundial/user/models.py
from django.contrib.auth.models import User
from django.db import models


class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='avatars', null=True, blank=True)

    def __str__(self):
        return f'url: {self.image.url}'

blog_mundial/user/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

from user.models import Avatar


class UserRegisterForm(UserCreationForm):

    username = forms.CharField(label='username', min_length=3)
    first_name = forms.CharField(label='Nombre', min_length=3)
    last_name = forms.CharField(label='Apellido', min_length=3)
    email = forms.EmailField(label='Correo electrónico')
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repetir la contraseña', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
        help_texts = {k: "" for k in fields}


class UserEditForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name' ]
        widgets = {
            'email': forms.TextInput(attrs={'readonly': 'readonly'}),
        }


class AvatarForm(ModelForm):
    class Meta:
        model = Avatar
        fields = ('image', )

blog_mundial/user/views.py
import os
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.forms.models import model_to_dict
from django.shortcuts import redirect, render


from user.forms import UserRegisterForm, UserEditForm, AvatarForm
from user.models import Avatar


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Usuario creado exitosamente!")
            return redirect("user:user-login")
    form = UserRegisterForm()
    return render(
        request=request,
        context={"form":form},
        template_name="user/register.html",
    )


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("home:main")

        return render(
            request=request,
            context={'form': form},
            template_name="user/login.html",
        )

    form = AuthenticationForm()
    return render(
        request=request,
        context={'form': form},
        template_name="user/login.html",
    )


def logout_request(request):
      logout(request)
      return redirect("user:user-login")


@login_required
def user_update(request):
    user = request.user
    if request.method == 'POST':
        form = UserEditForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()

            return redirect('home:main')

    form= UserEditForm(model_to_dict(user))
    return render(
        request=request,
        context={'form': form},
        template_name="user/user_form.html",
    )


@login_required
def avatar_load(request):
    if request.method == 'POST':
        form = AvatarForm(request.POST, request.FILES)
        if form.is_valid  and len(request.FILES) != 0:
            image = request.FILES['image']
            avatars = Avatar.objects.filter(user=request.user.id)
            if not avatars.exists():
                avatar = Avatar(user=request.user, image=image)
            else:
                avatar = avatars[0]
                if len(avatar.image) > 0:
                    os.remove(avatar.image.path)
                avatar.image = image
            avatar.save()
            messages.success(request, "Imagen cargada exitosamente")
            return redirect('home:main')

    form= AvatarForm()
    return render(
        request=request,
        context={"form": form},
        template_name="user/avatar_form.html",
    )

blog_mundial/user/templates/user/avatar_form.html
{% extends "home/index.html" %}
{% load static %}
{% block blog_mundial_content %}

<h2>Formulario para carga de Imagen de Avatar</h2>
<hr></hr>
<h3>Usuario: {{user.username}}</h3>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Cargar Imagen</button>
</form>

{% endblock %}

blog_mundial/user/templates/user/login.html
{% extends "home/index.html" %}
{% load static %}
{% block blog_mundial_content %}

<h2>Login</h2>
<hr></hr>

{% if form.errors %}
<p style="color: red">Combinación de username y password incorrecta, intenta de nuevo.</p>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <a class="btn2 btn-dark" href="{% url 'user:user-register' %}" >Registo</a>
    <button type="submit">Iniciar Sesión</button>
</form>

{% endblock %}

blog_mundial/user/templates/user/register.html
{% extends "home/index.html" %}
{% load static %}
{% block blog_mundial_content %}

<h2>Registro</h2>
<hr></hr>

{% if form.errors %}
<p style="color: red">Por favor diligenciar la forma completa.</p>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Registrar Usuario</button>
</form>

{% endblock %}

blog_mundial/user/templates/user/user_form.html
{% extends "home/index.html" %}
{% load static %}
{% block blog_mundial_content %}

<h2>Formulario para editar usuarios</h2>
<hr></hr>
<h3>Usuario: {{user.username}}</h3>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Guardar Usuario" />
    
</form>

{% endblock %}